fixtures:
  repositories:
    concat: "git://github.com/puppetlabs/puppetlabs-concat"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    apt:    "git://github.com/puppetlabs/puppetlabs-apt"
    apache: "https://github.com/puppetlabs/puppetlabs-apache.git"
