fixtures:
  repositories:
    concat: "git://github.com/puppetlabs/puppetlabs-concat"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    apt:    "git://github.com/puppetlabs/puppetlabs-apt"
    haproxy: "https://github.com/puppetlabs/puppetlabs-haproxy.git"
